### ISSUE TITLE
No config files get created - 1.10.2

### ISSUE THREAD

**Issue by Nazenn** [nfinit-gaming/Nether-Metals#10]
I'm not having any config files spawn in my OreSpawn folder in minecraft version 1.10.2 as the description suggests their should. The problem is also happening with End Metals. 

Have restarted my game several times and made multiple new worlds, the mod shows up in the forge mods listing, and tested on a game without any other mods to ensure its not a conflict. The mods show up fine, and there's no weird conflicts in regards to ores spawning where they shouldn't. Also making sure I'm using the 1.10 Orespawn instead of the 2.0 alpha as you suggested to other people. 

Here's my latest log if it helps at all, just jumped in a vanilla game with only those mods on a normal survival world and waited for a bit before quitting: http://paste.ee/p/mOHWD

**Comment by knoxhack** [comment]
What version exactly are you using? OreSpawn 2 creates the config folder under the root folder /orespawn and OreSpawn 1 creates it under /config/orespawn

**Comment by Nazenn** [comment]
The file finally showed up. Deleted the jar's (again) and redownloaded/installed them (again) and on rerunning it again they were created. Not sure if the issue was a corrupted download or something but its working now as expected. Sorry for the redundant report.
