### ISSUE TITLE
orespawn folder doesn't seem to generate

### ISSUE THREAD

**Issue by seanianjones** [nfinit-gaming/Nether-Metals#12]
MC 1.10.2
Forge 12.18.2.2151
1.9-1.1.2

(Possibly a separate issue that when downloading NetherMetals_1.10.2-1.1.2 on the Curse App I got NetherMetals_1.9-1.1.2)

The orespawn folder isn't in my config folder to add spawning for modded ores from Forestry and IC2.

**Comment by iLexiconn** [comment]
What version of orespawn are you using?

**Comment by seanianjones** [comment]
The NetherMetals .jar is 1.9-1.1.2

Version of orespawn?  Is orespawn a dependency?

**Comment by iLexiconn** [comment]
If you want to customize the spawning, yes

**Comment by seanianjones** [comment]
Alright, it wasn't listed on CurseForge, the Curse App or in the README.  Thanks!
