### ISSUE TITLE
Use "Ore" ore dictionary Tag (Suggestion) 

### ISSUE THREAD

**Issue by KidMessiah** [nfinit-gaming/Nether-Metals#13]
This would allow some quarries that detect ores to pick up your ores. As it seems this doesn't work currently, specifically with the Digital Miner unless you use the Mod ID filter instead.

**Comment by jriwanek** [comment]
That would make sense, but assigning ore<Something> to the nether ores would mean they'd be equivilent to normal ores, they'd need something like oreNether<something>

**Comment by jriwanek** [comment]
All nether ores are now oreNether<Material>
