### ISSUE TITLE
Crash Report for 1.1.3

### ISSUE THREAD

**Issue by DeathRaye** [nfinit-gaming/Nether-Metals#21]
Just updated from 1.1.2 to 1.1.3

[crash-2017-03-13_17.52.53-client.txt](https://github.com/MinecraftModDevelopmentMods/NetherMetals/files/839745/crash-2017-03-13_17.52.53-client.txt)

Forge 12.18.3.2254

**Comment by knoxhack** [comment]
you are missing a required mod: Mod orespawn

**Comment by DeathRaye** [comment]
Is that new?  I didn't have it for the 1.1.2 version.     Where do I get it from?

**Comment by knoxhack** [comment]
https://minecraft.curseforge.com/projects/mmd-orespawn
