### ISSUE TITLE
NetherMetals will crash the game when Mekanism digital miner is on

### ISSUE THREAD

**Issue by Pyrom4nia** [nfinit-gaming/Nether-Metals#23]
[crash-2017-03-12_14.15.17-server.txt](https://github.com/MinecraftModDevelopmentMods/NetherMetals/files/849572/crash-2017-03-12_14.15.17-server.txt)
When I open the Mekanism digital miner with Nether Metals, it will crash the game

**Comment by Pyrom4nia** [comment]
It's in 1.10.2

**Comment by knoxhack** [comment]
This was fixed in version 1.1.4. are you using that version?

**Comment by jriwanek** [comment]
Can't be, update to 1.1.4, that'll fix it.
