### ISSUE TITLE
Base-metals dependency is not marked as optional

### ISSUE THREAD

**Issue by Baughn** [nfinit-gaming/Nether-Metals#28]
You've got it as a required dependency on Curse. It should be optional.

**Comment by dshadowwolf** [comment]
For the version available right now (if memory serves) BaseMetals *IS* required, as it contains a set of common routines that are being split into a separate library.

I have to mark thus as a non-issue - the text in the description marking BaseMetals as optional is not correct for the 1.10.2 versions. This has largely simplified the code base, removing a lot of maintenance effort from @knoxhack but, as version 2.5 of BaseMetals nears release, also adds a lot of functionality, such as Tinkers' Construct, Thermal Expansion, Mekanism and Ender IO integration.

@knoxhack I'll leave it up to you whether this gets closed or not, but it isn't a valid bug, so much as a reminder that the projects page on CurseForge needs updating.
