### ISSUE TITLE
[1.12.2] Nether Iron can't be mined with a stone-level pickaxe

### ISSUE THREAD

**Issue by trainzkid** [nfinit-gaming/Nether-Metals#44]
Just as the title says.. I used a vanilla stone pickaxe, and it just mines very slowly and then breaks without dropping anything. All other ores can be mined (tested gold, copper, and lapis so far) with a stone pickaxe, which technically is a little off (vanilla requires an iron pick before gold can be mined) but at least it mines and drops the correct item. Diamond also functions correctly, it can't be mined with a stone pick.

NetherMetals v1.2.0-beta1.15
Forge v14.23.1.2568

**Comment by jriwanek** [comment]
Nor is it supposed to be able to, Nether ores are harder than their overworld equivalents.
