### ISSUE TITLE
[1.12.2] Non-Nether Ores ores yield nothing when placed into Chemical Injection Chambers and Purification Chambers.

### ISSUE THREAD

**Issue by Spearkiller** [nfinit-gaming/Nether-Metals#46]
Title.
Basically, Nether Iron, Gold, Copper, Tin, Silver, Lead all yield nothing when placed into a purification chamber or Chemical injection chamber. You can place them in there, they will process, but produce nothing.

Tested on 1.2.0-beta1.15

**Comment by jriwanek** [comment]
Fixed in dev for all but:
silver
gold
iron
osmium
copper
tin
lead

**Comment by dshadowwolf** [comment]
PR #55 fixes this in -dev
