### ISSUE TITLE
Vanilla ore generation

### ISSUE THREAD

**Issue by tgstyle** [nfinit-gaming/Nether-Metals#6]
I have disabled Orespawn standard ore generation, vanilla nether ores still generate. There is no json to control them either, is this what is intended?

**Comment by tgstyle** [comment]
https://github.com/jriwanek/End-Metals/issues/1

**Comment by jriwanek** [comment]
Currently yes, next version (for 1.9.4) will be able to use the orespawn library for vanilla generation.

**Comment by knoxhack** [comment]
Nether Metals MC 1.8.9 updated to version 1.1.1 now with a config file, I'm about to update the 1.9 branch

**Comment by knoxhack** [comment]
Config file added to the 1.9.x branch https://github.com/nfinit-gaming/Nether-Metals/commit/97aa2a4bf56b9b85b9b4ce3ad9cf36486d17971e  http://minecraft.curseforge.com/projects/nether-metals/files

**Comment by tgstyle** [comment]
Thanks for the unexpected quick turn around!

**Comment by tgstyle** [comment]
Just a quick note in the config, it has two Diamond options

general {
    I:NetherCoalOreSpawnProb=0
    I:NetherDIamondOreSpawnProb=0
    I:NetherDiamondOreSpawnProb=0
    I:NetherEmeraldOreSpawnProb=0
    I:NetherGoldOreSpawnProb=0
    I:NetherICoalOreSpawnProb=0
    I:NetherIronOreSpawnProb=0
    I:NetherLapisOreSpawnProb=0
    I:NetherRedstoneOreSpawnProb=0
}

**Comment by knoxhack** [comment]
I noticed, I have been coding all day I might have missed something, It shouldn't affect anything tho. I'll clean that out before the next version

**Comment by knoxhack** [comment]
I just made a quick hotfix for it, reset your configs and install version 1.1.2
