### ISSUE TITLE
Crash with latest java/forge java.lang.NoClassDefFoundError: com/mcmoddev/lib/events/MMDLibRegisterBlocks

### ISSUE THREAD

**Issue by donqixot** [nfinit-gaming/Nether-Metals#61]
I have separate instance with only NetherMetals-1.12-1.2.0-beta4.65 and OreSpawn-1.12-3.3.0.155. I have latest java 1.8.0_181, tried different forge version from "release" 14.23.4.2705 to latest 14.23.4.2765. I am getting

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: com/mcmoddev/lib/events/MMDLibRegisterBlocks
	at net.minecraftforge.fml.common.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:89)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:599)
...

see full crash report below.
[crash-2018-10-03_14.33.54-client.txt](https://github.com/MinecraftModDevelopmentMods/NetherMetals/files/2443335/crash-2018-10-03_14.33.54-client.txt)

**Comment by jriwanek** [comment]
If you're going to insist on trying to use nethermetals without basemetals, it's not going to work.
a later version of nether metals will support working without basemetals, the current version does not.

Also, you've clearly used a repost site, DONT use repost sites, support will not be provided.

**Comment by donqixot** [comment]
Thanks, I will try to include base metals. What do you mean by repost sites? I downloaded from curseforge https://minecraft.curseforge.com/projects/nether-metals/files/2618208

**Comment by jriwanek** [comment]
Orespawn, not nethermetals, all our builds are signed, your log says that orespawn isn't signed.

**Comment by donqixot** [comment]
Not sure why, I got it from curseforge as well. https://minecraft.curseforge.com/projects/mmd-orespawn/files/2616297

**Comment by jriwanek** [comment]
We'll double check it all, but I did grab it after you last replied and it does *appear* to have the sig data intact. I'm wondering if curse are pissing with the jars again...

**Comment by durandj** [comment]
Why not just mark BaseMetals as a dependency of this mod?
